name: Calling Workflow

on:
  release:
    types:
      - released

  workflow_dispatch:
    inputs:
      release-tag:
        description: 'The git tag of the release (e.g., v1.1.2).'
        required: true
        type: string

jobs:
  call_workflow:
    name: 'Call workflow'
    uses: ./.github/workflows/callable_workflow.yaml
#    with:
#      git-ref: ${{ github.event_name == 'workflow_dispatch' && inputs.release-tag || github.ref_name }}
