name: Test to setup Python workflow

on:
  workflow_dispatch:
    inputs:
      python-version-semver:
        description: 'python semver string'
        required: true
        type: string

jobs:
  set-up-python:
    name: Setup Python
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Set up Python test with different python-version strings
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version-semver }}
