name: Test to setup Python workflow

on:
  workflow_dispatch:
    inputs:
      python-version-semver:
        description: 'python semver string'
        required: true
        type: string
        default: '3.11'

env:
  BOOLEAN_VALUE_TRUE: true
  BOOLEAN_VALUE_FALSE: false

jobs:
  set-up-python:
    name: Setup Python
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Execute depending on value of BOOLEAN_VALUE_TRUE [BOOLEAN_VALUE_TRUE=${{ env.BOOLEAN_VALUE_TRUE }}]
        if: ${{ env.BOOLEAN_VALUE_TRUE }}
        run: echo BOOLEAN_VALUE_TRUE=${{ env.BOOLEAN_VALUE_TRUE }}
      
      - name: Execute depending on value of BOOLEAN_VALUE_FALSE [BOOLEAN_VALUE_FALSE=${{ env.BOOLEAN_VALUE_FALSE }}]
        if: ${{ env.BOOLEAN_VALUE_FALSE }}
        run: echo BOOLEAN_VALUE_FALSE=${{ env.BOOLEAN_VALUE_FALSE }}

      - name: Execute depending on value of BOOLEAN_VALUE_TRUE [BOOLEAN_VALUE_TRUE=${{ env.BOOLEAN_VALUE_TRUE }}]
        if: ${{ env.BOOLEAN_VALUE_TRUE == 'true' }}
        run: echo BOOLEAN_VALUE_TRUE=${{ env.BOOLEAN_VALUE_TRUE }}
      
      - name: Execute depending on value of BOOLEAN_VALUE_FALSE [BOOLEAN_VALUE_FALSE=${{ env.BOOLEAN_VALUE_FALSE }}]
        if: ${{ env.BOOLEAN_VALUE_FALSE = 'false' }}
        run: echo BOOLEAN_VALUE_FALSE=${{ env.BOOLEAN_VALUE_FALSE }}

      - name: Set up Python test with different python-version strings
        uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python-version-semver }}"
